### ISSUE TITLE
Does `@accepts` support `*args`/`**kwargs`?

### ISSUE THREAD

**Issue by covertg** [mwshinn/paranoidscientist#2]
Hello!

I am hoping to use argument type checking in conjunction with arbitrary function arguments (`*args`/`**kwargs`). Is there currently a best-practices way to implement this in paranoid? I haven't been able to figure it out using `@accepts`, but I figure that I could be missing something, so wanted to ask here.

The best I have been able to do is a slightly hacky solution with `@requires`. It relies on updating the namespace in order to use the desired paranoid types in the `eval` statement. E.g.,
```python
import math
from paranoid import Number, paranoidconfig, requires, settings

namespace_old = settings.Settings.get('namespace')
namespace = {**namespace_old, 'Number': Number}

@paranoidconfig(namespace=namespace)
@requires('all([arg in Number() for arg in args])')
def func(*args):
    pass

func(10)        # Good
func(10, 13)    # Good
func(math.nan)  # Error
```

**Comment by mwshinn** [comment]
The way you have described above is unfortunately currently the best way of doing it.  In general, it is assumed that not all elements of args/kwargs will be the same type, and so finding a way to specify all possible types for args/kwargs would get messy really quickly.  Also, the idea that a variable is known and expected to be in args/kwargs is a strange stylistic issue: I know there are a few use cases for it, but the idea is that if you know something is expected to be passed, it can be passed as a named argument.
